### ISSUE TITLE
Custom capabilities for cache purging (from WP_AdminBar)

### ISSUE THREAD

**Issue by jphorn** [Servebolt/servebolt-optimizer#226] opened 2021-06-17 10:22 UTC
Hi. Would it be feasible to introduce custom capabilities for the Cache Purge actions (mainly for the AdminBar part). We need to give our Editors access to the cache purging (esp. “Current Page cache” from AdminBar) to deal with social meta/images not always updating after post updates. Right now this is tied to manage_options cap.

https://github.com/Servebolt/servebolt-optimizer/blob/a95831af552f9edfe64be3c6615fd8c46bf73437/src/Servebolt/Admin/AdminBarGUI/AdminBarGUI.php#L42-L50

I couldn’t find any custom plugin capabilities with User Role Editor (which is the capabilites plugin we’re using)

**Comment by roberts91** [comment] 2021-06-17 13:47
Hello! Yes you are right, we're using "manage_options" for all capability checks. This is not ideal, but was done so to save some time early in the development process. I created a ticket (for the record WPSO-278) so we can track this issue internally. I'll get back to you when I know more. Thanks for reporting.

**Comment by roberts91** [comment] 2021-06-23 13:09
Hello again! I cannot promise anything, be so far we've planned to address and fix this issue in version 3.2. I'll get back to you when I know more.
- Robert

**Comment by roberts91** [comment] 2021-07-14 09:11
Hello again! I'm working on this issue as of now. It will be fixed in v3.2. No release date yet unfortunately.

**Comment by roberts91** [comment] 2021-07-15 14:29
Hello again!

I can confirm that the issue is addressed and the solution is available in the develop branch. We're entering a test phase for version 3.2 and as soon as that version is release you should have a more fine grained control over who can purge cache or not.

So:
- Administrators and editors can purge everything, using the capability "edit_others_posts".
- Authors can purge their own posts and terms. For post we're using the capabilities "edit_published_posts" and "edit_post". For terms we're using capability "manage_{taxonomy-slug}".
- Contributors and subscribers cannot purge cache at all.

Filters to manipulate the cache purge feature:
```
// Override whether to display the cache purge menu in the WP Admin bar
add_filter('sb_optimizer_admin_bar_display_cache_purge_node', '__return_true');

// Override the capability check for the cache purge actions in the WP Admin bar
add_filter('sb_optimizer_can_purge_post_cache', function($postId) {
    return true;
});
add_filter('sb_optimizer_can_purge_term_cache', function($termId, $taxonomyObject) {
    return true;
});
add_filter('sb_optimizer_can_purge_all_cache', '__return_true');
add_filter('sb_optimizer_can_purge_all_network_cache', '__return_true');
add_filter('sb_optimizer_can_purge_cache_by_url', '__return_true');
```

There are also two other links in the WP Admin bar - link to the plugin settings page and link to the Servebolt Admin Panel (if hosted at Servebolt). Both of these uses the capability "manage_options". Note that they can be overridden with the following filters:
add_filter('sb_optimizer_admin_bar_display_control_panel_node', '__return_true');
add_filter('sb_optimizer_admin_bar_display_settings_node', '__return_true');

Kind regards
Robert

**Comment by roberts91** [comment] 2021-07-15 14:31
If interested - here is the revaped WP Admin Bar GUI-code: https://github.com/Servebolt/servebolt-optimizer/tree/v3.2/src/Servebolt/Admin/AdminBarGui

**Comment by jphorn** [comment] 2021-07-22 20:35
Hi. Sorry I missed this. Looking very promising. Can't wait for its release.

**Comment by roberts91** [comment] 2021-08-24 10:50
Hello again @jphorn !
We have now release v3.2 which contains the update related to capability checks for cache purge. I hope this meets your needs, and if not then please re-open this issue and we can further develop this feature.

Kind regards
Robert

**Closed by roberts91** 2021-08-24 10:50 UTC
